# Change these first
owner: whosawhosa # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AppleDaily台灣蘋果日報
    url: https://tw.appledaily.com
  - name: ET-Today新聞雲
    url: https://www.ettoday.net/
  - name: SETN三立新聞
    url: https://www.setn.com/
  - name: CHINATIMES中時新聞網
    url: https://www.chinatimes.com/?chdtv
  - name: TVBS新聞網
    url: https://www.tvbs.com.tw/
  - name: MirrorMedia鏡週刊
    url: https://www.mirrormedia.mg/
  - name: UDN聯合新聞網
    url: https://udn.com/news/index
  - name: Yahoo奇摩新聞
    url: https://tw.news.yahoo.com/
  - name: LTN自由時報電子報
    url: https://www.ltn.com.tw/
  - name: NOWnews今日新聞
    url: https://www.nownews.com/
  - name: newtalk新頭殼
    url: https://newtalk.tw/
  - name: TechNews 科技新報
    url: https://technews.tw/
  - name: businessweekly商業週刊
    url: https://www.businessweekly.com.tw/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: news.drekay.com
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: 目前異常事件
  pastIncidents: 過去的異常事件
  incidentDetails: 事件細節
  incidentFixed: 已修復
  incidentOngoing: 尚未修復
